package models;
// Generated Feb 9, 2016 11:43:06 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nalaz generated by hbm2java
 */
public class Nalaz  implements java.io.Serializable {


     private int id;
     private Date datumNalaza;
     private Integer disanje;
     private Integer puls;
     private Integer telesnaTemperatura;
     private String krvniPritisak;
     private String mokraca;
     private String stolica;
     private String krvnaSlika;
     private String specificanPregled;

    public Nalaz() {
    }

	
    public Nalaz(int id) {
        this.id = id;
    }
    public Nalaz(int id, Date datumNalaza, Integer disanje, Integer puls, Integer telesnaTemperatura, String krvniPritisak, String mokraca, String stolica, String krvnaSlika, String specificanPregled) {
       this.id = id;
       this.datumNalaza = datumNalaza;
       this.disanje = disanje;
       this.puls = puls;
       this.telesnaTemperatura = telesnaTemperatura;
       this.krvniPritisak = krvniPritisak;
       this.mokraca = mokraca;
       this.stolica = stolica;
       this.krvnaSlika = krvnaSlika;
       this.specificanPregled = specificanPregled;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getDatumNalaza() {
        return this.datumNalaza;
    }
    
    public void setDatumNalaza(Date datumNalaza) {
        this.datumNalaza = datumNalaza;
    }
    public Integer getDisanje() {
        return this.disanje;
    }
    
    public void setDisanje(Integer disanje) {
        this.disanje = disanje;
    }
    public Integer getPuls() {
        return this.puls;
    }
    
    public void setPuls(Integer puls) {
        this.puls = puls;
    }
    public Integer getTelesnaTemperatura() {
        return this.telesnaTemperatura;
    }
    
    public void setTelesnaTemperatura(Integer telesnaTemperatura) {
        this.telesnaTemperatura = telesnaTemperatura;
    }
    public String getKrvniPritisak() {
        return this.krvniPritisak;
    }
    
    public void setKrvniPritisak(String krvniPritisak) {
        this.krvniPritisak = krvniPritisak;
    }
    public String getMokraca() {
        return this.mokraca;
    }
    
    public void setMokraca(String mokraca) {
        this.mokraca = mokraca;
    }
    public String getStolica() {
        return this.stolica;
    }
    
    public void setStolica(String stolica) {
        this.stolica = stolica;
    }
    public String getKrvnaSlika() {
        return this.krvnaSlika;
    }
    
    public void setKrvnaSlika(String krvnaSlika) {
        this.krvnaSlika = krvnaSlika;
    }
    public String getSpecificanPregled() {
        return this.specificanPregled;
    }
    
    public void setSpecificanPregled(String specificanPregled) {
        this.specificanPregled = specificanPregled;
    }




}


