package models;
// Generated Feb 9, 2016 11:43:06 AM by Hibernate Tools 4.3.1



/**
 * SpecijalistaTip generated by hbm2java
 */
public class SpecijalistaTip  implements java.io.Serializable {


     private Integer id;
     private String ime;
     private Integer prioritet;

    public SpecijalistaTip() {
    }

	
    public SpecijalistaTip(String ime) {
        this.ime = ime;
    }
    public SpecijalistaTip(String ime, Integer prioritet) {
       this.ime = ime;
       this.prioritet = prioritet;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public Integer getPrioritet() {
        return this.prioritet;
    }
    
    public void setPrioritet(Integer prioritet) {
        this.prioritet = prioritet;
    }




}


