package models;
// Generated Feb 9, 2016 11:43:06 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Uput generated by hbm2java
 */
public class Uput  implements java.io.Serializable {


     private Integer id;
     private Date datumPregleda;
     private int klinikaId;
     private int pacijentId;
     private int specijalistaTipId;
     private int pregledan;

    public Uput() {
    }

    public Uput(Date datumPregleda, int klinikaId, int pacijentId, int specijalistaTipId, int pregledan) {
       this.datumPregleda = datumPregleda;
       this.klinikaId = klinikaId;
       this.pacijentId = pacijentId;
       this.specijalistaTipId = specijalistaTipId;
       this.pregledan = pregledan;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDatumPregleda() {
        return this.datumPregleda;
    }
    
    public void setDatumPregleda(Date datumPregleda) {
        this.datumPregleda = datumPregleda;
    }
    public int getKlinikaId() {
        return this.klinikaId;
    }
    
    public void setKlinikaId(int klinikaId) {
        this.klinikaId = klinikaId;
    }
    public int getPacijentId() {
        return this.pacijentId;
    }
    
    public void setPacijentId(int pacijentId) {
        this.pacijentId = pacijentId;
    }
    public int getSpecijalistaTipId() {
        return this.specijalistaTipId;
    }
    
    public void setSpecijalistaTipId(int specijalistaTipId) {
        this.specijalistaTipId = specijalistaTipId;
    }
    public int getPregledan() {
        return this.pregledan;
    }
    
    public void setPregledan(int pregledan) {
        this.pregledan = pregledan;
    }




}


